dbt_prop_e2e:
    target: local
    outputs:
      local:
        type: postgres
        threads: 1
        host: localhost
        port: 5432
        user: postgres
        pass: postgres
        dbname: prop-e2e-dbt
        schema: analysis

