version: '3.8'
services:
    postgres:
        image: postgres:latest
        restart: unless-stopped
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=prop-e2e-dbt
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5432:5432'
        volumes: 
          - ./postgres_data:/var/lib/postgresql/data